name: stacked_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  stacked: ^2.3.15+1
  stacked_services: ^0.9.5
  firebase_core: ^1.22.0
  firebase_auth: ^3.7.0
  stacked_firebase_auth: ^0.2.16
  auth_buttons: ^3.0.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  cloud_firestore: ^3.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.7.15
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro-Light.ttf
        - asset: assets/fonts/SFPro-Regular.ttf
        - asset: assets/fonts/SFPro-Medium.ttf
        - asset: assets/fonts/SFPro-Semibold.ttf
        - asset: assets/fonts/SFPro-Bold.ttf
        - asset: assets/fonts/SFPro-Heavy.ttf
